### ISSUE TITLE
Modificaiton of authentication function in 1.0.5

### ISSUE THREAD

**Issue by flytianwu** [app-generator/django-soft-ui-dashboard-pro#1]
Hi, team, 

The /apps/ folder in the root dictionary has been removed in 1.0.5, which has /apps/authentication/, /apps/templates/, etc. 
What can I do if I want to modify the authentication or templates now? 
I want to change the registration form( use email as username) and add email verification to it. Also, add some email templates to the templates folder. 
Thank you in advance. 

Best regards, 
Gary

**Comment by flytianwu** [comment]
Thank you for the support from Discord! 
Now I know that I need to rewrite all the templates and views model for the 1.0.5 version.

**Comment by app-generator** [comment]
Hello @flytianwu 

Let us know if you need further assistance. 
🚀🚀
