### ISSUE TITLE
Bad div arrangement in mobile-view menu pop-out

### ISSUE THREAD

**Issue by elementace** [app-generator/django-soft-ui-dashboard-pro#2]
You can see in the screenshots attached, while in mobile view the menu pop-out creates some undesirable looks with the logos/headings and search bar

<img width="349" alt="Screen Shot 2021-09-12 at 4 32 49 pm" src="https://user-images.githubusercontent.com/19167639/132976468-a81eb35b-c02f-4859-82f0-e177d3894d32.png">
<img width="291" alt="Screen Shot 2021-09-12 at 4 32 41 pm" src="https://user-images.githubusercontent.com/19167639/132976475-1c991e6d-13ff-42a9-a8d9-98c233616eaf.png">

**Comment by app-generator** [comment]
Fixed in version **v1.0.3**. 

LIVE demo: https://django-soft-ui-dashboard-pro.appseed-srv1.com/

Closing.
